# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 550)
        MainWindow.setMaximumSize(QtCore.QSize(312, 550))
        MainWindow.setStyleSheet("/* -------------------------\n"
"  GENERAL\n"
"   ------------------------- */\n"
"QWidget{\n"
"    background-color: #2C2C2E;\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:white;\n"
"}\n"
"\n"
"/* -------------------------\n"
"   BOTONES NUMÉRICOS (0–9)\n"
"   ------------------------- */\n"
"QPushButton[class=\'num_btn\'] {\n"
"    background-color: #3A3A3C;\n"
"    color: white;\n"
"    font-size: 22px;\n"
"    border-radius: 28px;\n"
"    min-width: 56px;\n"
"    min-height: 56px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton[class=\'num_btn\']:pressed {\n"
"    background-color: #505052;\n"
"}\n"
"\n"
"/* -------------------------\n"
"   BOTONES DE FUNCIONES CLARAS\n"
"   (AC, ±, %, clear, etc.)\n"
"   ------------------------- */\n"
"QPushButton[class=\'func_btn\'] {\n"
"    background-color: #A5A5A7;\n"
"    color: black;\n"
"    font-size: 20px;\n"
"    border-radius: 28px;\n"
"    min-width: 56px;\n"
"    min-height: 56px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton[class=\'func_btn\']:pressed {\n"
"    background-color: #C6C6C8;\n"
"}\n"
"\n"
"/* -------------------------\n"
"   BOTONES DE OPERACIÓN\n"
"   (+, –, ×, ÷, =)\n"
"   ------------------------- */\n"
"QPushButton[class=\'op_btn\'] {\n"
"    background-color: #FF9500;\n"
"    color: white;\n"
"    font-size: 22px;\n"
"    border-radius: 28px;\n"
"    min-width: 56px;\n"
"    min-height: 56px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton[class=\'op_btn\']:pressed {\n"
"    background-color: #CC7A00;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_section = QtWidgets.QFrame(self.centralwidget)
        self.output_section.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_section.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_section.setObjectName("output_section")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.output_section)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.output_label = QtWidgets.QLabel(self.output_section)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.verticalLayout_6.addWidget(self.output_label)
        self.output = QtWidgets.QLabel(self.output_section)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.output.setFont(font)
        self.output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        self.verticalLayout_6.addWidget(self.output)
        self.verticalLayout.addWidget(self.output_section)
        self.btn_section = QtWidgets.QFrame(self.centralwidget)
        self.btn_section.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_section.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_section.setObjectName("btn_section")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_section)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.col1 = QtWidgets.QVBoxLayout()
        self.col1.setObjectName("col1")
        self.btn_remove = QtWidgets.QPushButton(self.btn_section)
        self.btn_remove.setObjectName("btn_remove")
        self.col1.addWidget(self.btn_remove)
        self.btn_7 = QtWidgets.QPushButton(self.btn_section)
        self.btn_7.setObjectName("btn_7")
        self.col1.addWidget(self.btn_7)
        self.btn_4 = QtWidgets.QPushButton(self.btn_section)
        self.btn_4.setObjectName("btn_4")
        self.col1.addWidget(self.btn_4)
        self.btn_1 = QtWidgets.QPushButton(self.btn_section)
        self.btn_1.setObjectName("btn_1")
        self.col1.addWidget(self.btn_1)
        self.comodin = QtWidgets.QPushButton(self.btn_section)
        self.comodin.setObjectName("comodin")
        self.col1.addWidget(self.comodin)
        self.horizontalLayout_2.addLayout(self.col1)
        self.col2 = QtWidgets.QVBoxLayout()
        self.col2.setObjectName("col2")
        self.btn_clear_all = QtWidgets.QPushButton(self.btn_section)
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.col2.addWidget(self.btn_clear_all)
        self.btn_8 = QtWidgets.QPushButton(self.btn_section)
        self.btn_8.setObjectName("btn_8")
        self.col2.addWidget(self.btn_8)
        self.btn_5 = QtWidgets.QPushButton(self.btn_section)
        self.btn_5.setObjectName("btn_5")
        self.col2.addWidget(self.btn_5)
        self.btn_2 = QtWidgets.QPushButton(self.btn_section)
        self.btn_2.setObjectName("btn_2")
        self.col2.addWidget(self.btn_2)
        self.btn_0 = QtWidgets.QPushButton(self.btn_section)
        self.btn_0.setObjectName("btn_0")
        self.col2.addWidget(self.btn_0)
        self.horizontalLayout_2.addLayout(self.col2)
        self.col3 = QtWidgets.QVBoxLayout()
        self.col3.setObjectName("col3")
        self.btn_percent = QtWidgets.QPushButton(self.btn_section)
        self.btn_percent.setObjectName("btn_percent")
        self.col3.addWidget(self.btn_percent)
        self.btn_9 = QtWidgets.QPushButton(self.btn_section)
        self.btn_9.setObjectName("btn_9")
        self.col3.addWidget(self.btn_9)
        self.btn_6 = QtWidgets.QPushButton(self.btn_section)
        self.btn_6.setObjectName("btn_6")
        self.col3.addWidget(self.btn_6)
        self.btn_3 = QtWidgets.QPushButton(self.btn_section)
        self.btn_3.setObjectName("btn_3")
        self.col3.addWidget(self.btn_3)
        self.btn_comma = QtWidgets.QPushButton(self.btn_section)
        self.btn_comma.setObjectName("btn_comma")
        self.col3.addWidget(self.btn_comma)
        self.horizontalLayout_2.addLayout(self.col3)
        self.col4 = QtWidgets.QVBoxLayout()
        self.col4.setObjectName("col4")
        self.btn_division = QtWidgets.QPushButton(self.btn_section)
        self.btn_division.setObjectName("btn_division")
        self.col4.addWidget(self.btn_division)
        self.btn_mult = QtWidgets.QPushButton(self.btn_section)
        self.btn_mult.setObjectName("btn_mult")
        self.col4.addWidget(self.btn_mult)
        self.btn_subs = QtWidgets.QPushButton(self.btn_section)
        self.btn_subs.setObjectName("btn_subs")
        self.col4.addWidget(self.btn_subs)
        self.btn_plus = QtWidgets.QPushButton(self.btn_section)
        self.btn_plus.setObjectName("btn_plus")
        self.col4.addWidget(self.btn_plus)
        self.btn_equals = QtWidgets.QPushButton(self.btn_section)
        self.btn_equals.setObjectName("btn_equals")
        self.col4.addWidget(self.btn_equals)
        self.horizontalLayout_2.addLayout(self.col4)
        self.verticalLayout.addWidget(self.btn_section)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 312, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.output_label.setText(_translate("MainWindow", "Super Calculadora Cientifica"))
        self.output.setText(_translate("MainWindow", "0"))
        self.btn_remove.setText(_translate("MainWindow", "DEL"))
        self.btn_remove.setProperty("class", _translate("MainWindow", "func_btn"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_7.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_4.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_1.setProperty("class", _translate("MainWindow", "num_btn"))
        self.comodin.setText(_translate("MainWindow", "+/ -"))
        self.comodin.setProperty("class", _translate("MainWindow", "func_btn"))
        self.btn_clear_all.setText(_translate("MainWindow", "AC"))
        self.btn_clear_all.setProperty("class", _translate("MainWindow", "func_btn"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_8.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_5.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_2.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_0.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_percent.setText(_translate("MainWindow", "%"))
        self.btn_percent.setProperty("class", _translate("MainWindow", "func_btn"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_9.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_6.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_3.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_comma.setText(_translate("MainWindow", ","))
        self.btn_comma.setProperty("class", _translate("MainWindow", "num_btn"))
        self.btn_division.setText(_translate("MainWindow", "/"))
        self.btn_division.setProperty("class", _translate("MainWindow", "op_btn"))
        self.btn_mult.setText(_translate("MainWindow", "X"))
        self.btn_mult.setProperty("class", _translate("MainWindow", "op_btn"))
        self.btn_subs.setText(_translate("MainWindow", "-"))
        self.btn_subs.setProperty("class", _translate("MainWindow", "op_btn"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_plus.setProperty("class", _translate("MainWindow", "op_btn"))
        self.btn_equals.setText(_translate("MainWindow", "="))
        self.btn_equals.setProperty("class", _translate("MainWindow", "op_btn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
